### ISSUE TITLE
Install aliexpress module -->> YD-RP2040 (vcc-gnd.com)

### ISSUE THREAD

**Issue by retroban** [danielinux/fidelio#1]
I tried to install this firmware on a device from aliexpress called YD-RP2040 (vcc-gnd.com). I changed the pin to the one to which the additional button on this scarf is connected. I assembled the project into firmware successfully. successfully stitched. When I try to use it, I get a message that the device status is unknown.

**Comment by danielinux** [comment]
Hi! Thanks for giving the project a chance. We have successfully tested the software on different rp2040 and changed the led/button pins accordingly.

Could you be more specific about the error you get, I'll be happy to help. If you have a linux box to test on, could you paste the relevant lines in `dmesg` when you connect the device, and/or the output of `lsusb -v -d 1209:F1DE`.

**Comment by retroban** [comment]
user@debian:~$ lsusb -v -d 1209:F1DE

Bus 001 Device 003: ID 1209:f1de Generic U2F-Fido rp2040
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x1209 Generic
  idProduct          0xf1de
  bcdDevice            1.00
  iManufacturer           1 Danielinux
  iProduct                2 U2F-Fido rp2040
  iSerial                 3 122023
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      34
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               5
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               5

**Comment by retroban** [comment]
user@debian:~$ fido2-token -L
/dev/hidraw1: vendor=0x1209, product=0xf1de (Danielinux U2F-Fido rp2040)
user@debian:~$ fido2-token -I /dev/hidraw1
proto: 0x01
major: 0x01
minor: 0x00
build: 0x00
caps: 0x00 (nowink, nocbor, msg)
user@debian:~$ fido2-token -S /dev/hidraw1
Enter new PIN for /dev/hidraw1:
Enter the same PIN again:
fido2-token: fido_dev_set_pin: FIDO_ERR_INTERNAL
user@debian:~$ fido2-token -L -r /dev/hidraw1
fido2-token: fido_credman_get_dev_rp: FIDO_ERR_INVALID_COMMAND
user@debian:~$ fido2-token -R /dev/hidraw1
(The process starts and nothing happens, so just cancel the task)

**Comment by danielinux** [comment]
All seems OK. The `fido2-token` util is not expected to work. I think that's a FIDO 2.0-only interface.
Have you tried `pamu2fcfg`  instead, as suggested in the README?

Does the test on https://demo.yubico.com/webauthn-technical/registration succeed?

**Comment by retroban** [comment]
But for example, the key from https://github.com/polhenarejos/pico-fido
His conclusion:

**Comment by retroban** [comment]
user@debian:~$ fido2-token -L
/dev/hidraw1: vendor=0x1050, product=0x0407 (Pol Henarejos Pico Key)
user@debian:~$ fido2-token -I /dev/hidraw1
proto: 0x02
major: 0x05
minor: 0x08
build: 0x00
caps: 0x05 (wink, cbor, msg)
version strings: U2F_V2, FIDO_2_0, FIDO_2_1
extension strings: credBlob, credProtect, hmac-secret, largeBlobKey, minPinLength, thirdPartyPayment
algorithms: es256 (public-key), es384 (public-key), unknown (public-key), unknown (public-key)
aaguid: 89fb94b706c936739b7e30526d968145
options: noep, rk, credMgmt, authnrCfg, clientPin, largeBlobs, pinUvAuthToken, setMinPINLength
fwversion: 0x508
maxmsgsiz: 1024
maxcredcntlst: 16
maxcredlen: 1024
maxlargeblob: 2048
minpinlen: 4
pin protocols: 1, 2
pin retries: 8
pin change required: false
uv retries: undefined
user@debian:~$ fido2-token -L -r /dev/hidraw1
Enter PIN for /dev/hidraw1:
00: 1MnZA..........................................Zk8= google.com
user@debian:~$ fido2-token -L -k google.com /dev/hidraw1
Enter PIN for /dev/hidraw1:
00: 8dACASQeCFrMfnaK5K4VvSd0n.............................8VJhKngG xxxxxxx@gmail.com R09PR0xFX0..................................1 es256 uvopt+id
01: 8dACAeHNNK9QNPO......................................3VBfmlBft0zpYlswFVms3od+mBDq0lVmwX0e9C4uEe9ukYs8F/Z6oZrJFTyaP7XGtOHNi2ODDKSiZ802oAuJ..............................................w= (null) R09PR0xFX0FDQ09VTlQ6MTA2MDI1MTExODUyMTYzNTIxMDk5 es256 unknown
user@debian:~$

**Comment by danielinux** [comment]
yes. That project supports FIDO-2.0. Fidelio is 1.2 only for now, as I decided to leave out the complexity of CBOR parsing, and FIDO 1.2 it's sufficiently supported for all my use cases.

**Comment by retroban** [comment]
https://demo.yubico.com/webauthn-technical/registration - I tried it, the button does not work, I compiled the firmware several times, it does not work with both user button is GP24 pin and GP15

**Comment by danielinux** [comment]
Are you sure you are connecting the button between GND and the pin you want to read from? Does the LED turn on when the registration is ongoing?

**Comment by retroban** [comment]
https://demo.yubico.com/webauthn-technical/registration (For Windows) -
![2024-03-12_161212](https://github.com/danielinux/fidelio/assets/37443866/d21196d8-b260-4459-b916-956c4e109b56)

**Comment by danielinux** [comment]
![image](https://github.com/danielinux/fidelio/assets/1027688/06f5ce3d-ead9-4a02-85e1-448f53e64fb0)

This is the page I'm getting after the registration
