### ISSUE TITLE
Why use a pin for the button?

### ISSUE THREAD

**Issue by peardox** [danielinux/fidelio#3]
Why not just use the BOOTSEL button?

See a [test app](https://github.com/peardox/pico_prime/blob/dea79d0d187e8f8fe67afff9e054171edf3fc59c/prime.c#L93) I wrote for an example

The original is in Pico SDK examples [here](https://github.com/raspberrypi/pico-examples/blob/master/picoboard/button/button.c)

Anyway, gonna definitely fork and switch to BOOTSEL myself...

**Comment by danielinux** [comment]
nice idea! Thanks, I did not know that was possible, although a bit hackish.

Why forking? I'd merge that in :)

**Comment by peardox** [comment]
I'll do both

Fork is more for doing the same on a Waveshare RP2040-GEEK - comes in a case and has a little screen you could use to show info on...

**Comment by danielinux** [comment]
Sounds great! Of course feel free to base other projects on it. I'll look forward to your bootsel option PR then. Thanks!
